---
- template:
    source:
      distribution: debian
      architecture: amd64
      version: 12
      variant: genericcloud
    target:
      name: debian-12-genericcloud-amd64
      cpu: 1
      memory: 1
      network: "Pool-wide network associated with eth1"
      sr: "Local storage - srv3"
- template:
    source:
      distribution: debian
      architecture: amd64
      version: 11
      variant: genericcloud
    target:
      name: debian-11-genericcloud-amd64
      cpu: 1
      memory: 1
      network: "Pool-wide network associated with eth1"
      sr: "Local storage - srv2"